/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/themed-view`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-color-scheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-theme-color`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/icon-symbol.ios`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/icon-symbol`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/themed-view`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/use-color-scheme.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/use-theme-color`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/icon-symbol.ios`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/icon-symbol`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../components/themed-view${`?${string}` | `#${string}` | ''}` | `/../hooks/use-color-scheme.web${`?${string}` | `#${string}` | ''}` | `/../hooks/use-theme-color${`?${string}` | `#${string}` | ''}` | `/../components/ui/icon-symbol.ios${`?${string}` | `#${string}` | ''}` | `/../components/ui/icon-symbol${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/themed-view`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-color-scheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-theme-color`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/icon-symbol.ios`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/icon-symbol`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
